<a href="https://colab.research.google.com/github/betoval/learning-tensorflow/blob/master/basic_easy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x
import tensorflow as tf
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])
#multiply entries
result = tf.multiply(x1,x2)
print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


The snipet multiply every entry of the vector

In [0]:
import tensorflow as tf
print("Tensorflow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version: 2.1.0
Eager execution is: True
Keras version: 2.2.4-tf


The eager execution is automatically included in TensorFlow 2

In [0]:
#matrix with two rows and three columns
#note the nested brackets
print("Tensorflow version: {}".format(tf.__version__))
tf.constant([[1.,2.,3.],[4.,5.,6.]])

Tensorflow version: 2.1.0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [0]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
v = tf.Variable([[1.,2.,3.], [4.,5.,6.]])
v.assign(2*v) #multiply every entry by 2
v[1, 1].assign(42) #assign the number 42 to the 1,1 entry of the matrix

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 42., 12.]], dtype=float32)>