<a href="https://colab.research.google.com/github/betoval/learning-tensorflow/blob/master/intro_tensorflow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
%tensorflow_version 2.x
import tensorflow as tf

var = tf.Variable([3,3])

#the command mentioned in the book is deprecated
#config.list is the new command
if tf.test.is_gpu_available():
  print('Running on GPU')
  print('GPU #0?')
  print(var.device.endswith('GPU:0'))
else:
  print('Running on CPU')

Running on CPU


If we choose GPU in the notebook settings, then we will obtain GPU as output (duh). However, we do not need a lot of resources right now, we will stick to CPU.

**Declaring eager variables, wtf is a tensor?, and all that preliminary stuff** 

The rank specifies the number of "dimensions" (n) of the tensor, that is, it indicates the number of indices that are required to specify a particular element of that tensor. For me, it is easier to think of tensors as n-forms. In the example below, we are talking about a 3-form, that is, an object with 3 indices.
If you want to visualize them, then think of tensors as matrices. In this example, we are working with a 3 dimensional matrix with 2 slices, 2 rows and 3 columns (this info is given by the shape of the tensor, that is, shape = (2, 2, 3)). Thus, if we want to assign a new value to an entry, then we need to specify three numbers corresponding to the slice, row and column.

In [22]:
#declaring eager variables
t0 = 24 #python variable
t1 = tf.Variable(42) # scalar or 0 rank tensor
#3-form or rank 3 tensor
t2 = tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) #datatype=float32
print(tf.rank(t2)) #print the rank of the tensor
t2[1,1,1].assign(33) #assign new value to the entry 1,1,1
print(t2.shape) #print shape of tensor
t0,t1,t2

tf.Tensor(3, shape=(), dtype=int32)
(2, 2, 3)


(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 33., 11.]]], dtype=float32)>)

**Reshaping a tensor**

The snippet below shows how to reshape a tensor. We took the already defined t2 tensor. In the first line we reshape it to a 2-form (rank 2 tensor), which can be visualized as a matrix with 2 rows and 6 columns. In the second line we did something similar.

In [26]:
#reshaping a tensor
r1 = tf.reshape(t2,[2,6]) #2 rows 6 columns
r2 = tf.reshape(t2,[1,12]) #1 rows 12 cols
r1,r2


(<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 33., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 12), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 33., 11.]],
       dtype=float32)>)

In [34]:
#Tensor as a numpy/python variable
print(t2.numpy())
print(t2[1,0,2].numpy())
#number of elements of a tensor (size)
s = tf.size(input = t2).numpy()
s

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 33. 11.]]]
8.0


12

**Operations between tensors.**

We can operate between the elements of a tensor using the operators +, -, * and /. They also accept broadcasting, that is, arithmetic operations between tensors of different shape (just like broadcasting in python/numpy between arrays of different shape). In the example below, we multiply a rank3 tensor by a scalar

In [39]:
#Tensor operations
t2*t2
#broadcasting
t4 = t2*4
print(t4)

tf.Tensor(
[[[  0.   4.   8.]
  [ 12.  16.  20.]]

 [[ 24.  28.  32.]
  [ 36. 132.  44.]]], shape=(2, 2, 3), dtype=float32)


**Matrix multiplication and transpose**

We use tf.matmul() to multiply matrices, and tf.trnaspose() to obtain the corresponding trnaspose matrix. Here, we define two row matrices u, v, then we consider the transpose of v. Finally, we multiply v*v^t. The result is a 1x1 matrix.

In [40]:
#matrix multiplication
u = tf.constant([[3,4,5]]) #row matrix
v = tf.constant([[1,2,1]]) #row matrix
tf.matmul(u,tf.transpose(a=v)) #multiply u with v transpose

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[16]], dtype=int32)>

**Ragged tensors**

A ragged tensor has one or more ragged dimensions. A ragged dimension is a property of the slices. It basically indicates that such slices may have different shapes as seen in the example below

In [41]:
#declare ragged constant array
ragged = tf.ragged.constant([[5,2,6,1],[],[4,10,7], [8], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)
